version: '3.7'

services: 
  dev :
    container_name: nk-react-app
    image: nankim/nk-react-app
    stdin_open: true
    command: npm run start
    environment: 
      - CHOKIDAR_USERPOLLING=true
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  prod :
    container_name: nk-react-app-prod
    image: nankim/nk-react-app-prod
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:80
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  
